### ISSUE TITLE
Reimplement CustomizeConnection::on_release()

### ISSUE THREAD

**Issue by paolobarbolini** [djc/bb8#103]
#94 implemented the equivalent of r2d2's [`on_release`](https://docs.rs/r2d2/0.8.9/r2d2/trait.CustomizeConnection.html#method.on_release) method, but reverted it before release.

This is exactly what we'd need for `lettre`. We have a PR https://github.com/lettre/lettre/pull/550 which implements connection pooling for the async version of our API. However, before dropping an SMTP connection, the client must send a `QUIT` command (see https://tools.ietf.org/html/rfc5321#section-4.1.1.10). My thinking is that `on_release` would be perfect for this use-case.

I'll later send a PR to reimplement `on_release`.

**Comment by djc** [comment]
Out of curiosity, what's your reason for closing this?

**Comment by paolobarbolini** [comment]
We ended up having our own pool implementation https://github.com/lettre/lettre/pull/637, which would also allow us to support both tokio and async-std

**Comment by djc** [comment]
Fair enough, thanks for the explanation!
