### ISSUE TITLE
when can we expect a new release?

### ISSUE THREAD

**Issue by NikosEfthias** [djc/bb8#121]
It seems for the past 2 years there weren't any releases. while things like tokio-postgres added support for time:0.3 support we are still stuck with time:0.2.
If updating often is not an option is it possible to use a little loser versioning for dependencies like postgres and redis.
I mean instead of using 0.7.0 for instance can we use 0.7 and have ability to support patches of wrapped libraries  without actually needing to update bb8 itself.
Builds would be still reliable for the existing code since cargo lockfile would lock the package to a particular version anyway

**Comment by djc** [comment]
I think you misunderstand how semantic versioning works in Rust. bb8-postgres depends on tokio-postgres 0.7 or later, but if you depend on bb8-postgres today that will trivially pull in tokio-postgres 0.7.5 with a cargo update. (In other words, the default in `Cargo.toml` is the `^` semver operator, even if not specified.) So, time 0.3 support should be available just fine with the current version of bb8-postgres.

**Comment by NikosEfthias** [comment]
Oh I thought for some reason bb8-postgres specifies 0.7.0 particularly sorry for the trouble :) so In theory I could pull a seperate tokio-postgres with time 0.3 support and use it with bb8-postgres just fine right

**Comment by djc** [comment]
Yes, though if you would just like a bb8-postgres 0.8.1 release done that's probably also fine? That wasn't quite clear to me from your original issue description (though maybe it should have been).

**Comment by djc** [comment]
Actually I just published a trio of new releases, bb8 0.8, bb8-postgres 0.8 and bb8-redis 0.11.0, so that should definitely take care of this/.
