### ISSUE TITLE
Support newer `uuid` version (1.x)

### ISSUE THREAD

**Issue by ChristianBeilschmidt** [djc/bb8#127]
The crate `uuid` recently updated first to `1.0` and then to `1.1`.
Unfortunately, `bb8-postgres` is still only compatible with `0.8`.

The dependency `tokio-postgres` has recently added the flag `with-uuid-1`.
As far as I see, `bb8-postgres` just passes this flag on to the dependency.

It would be nice to add the `with-uuid-1` flag accordingly to `bb8-postgres`.
Then, of course, it would be great to have a new release on crates.io.

**Comment by djc** [comment]
Would you be able to submit a PR for this to add the flag? Please add a separate commit that bumps the version.

**Comment by ChristianBeilschmidt** [comment]
I created a PR for that: https://github.com/djc/bb8/pull/128

**Comment by gabor-boros** [comment]
@djc shouldn't this issue be closed?
