### ISSUE TITLE
Question Regarding `has_broken` / bb8 usage 

### ISSUE THREAD

**Issue by jgould22** [djc/bb8#129]
I am looking to use bb8 to make a basic connection pool that holds a collection of open sockets(in the form of [tokio](https://docs.rs/tokio/latest/tokio/index.html)::[net](https://docs.rs/tokio/latest/tokio/net/index.html)::[TcpStream](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#)) to a remote server.

The issue is that as part of the remote servers protocol after it has accepted and completed a request it closes the socket and I need to open a new one for any new requests (can't change this behavior at the moment). I would like the pool to open a new socket whenever one is returned and place it back in the pool ready for use.

To this end I have just made `has_broken`  always return true which should cause the pool to discard the connection when it is returned and replace it. 

Are their any gotchas that I am missing with this approach ?

Here is a rough sample of my `ManageConnection` implementation for reference 

```rust
pub struct MyConnectionPool {
    addr: String,
    timeout: Duration,
}

#[async_trait]
impl bb8::ManageConnection for MyConnectionPool {
    type Connection = TcpStream;
    type Error = MyError;

    async fn connect(&self) -> Result<Self::Connection, Self::Error> {
        // Open a socket to the server, or return timeout error
        match timeout(self.timeout, TcpStream::connect(&self.addr)).await {
            Ok(Ok(stream)) => Ok(stream),
            Ok(Err(err)) => Err(err.into()),
            Err(Elapsed { .. }) => Err(MyError::SocketTimeout),
        }
    }

    async fn is_valid(&self, conn: &mut Self::Connection) -> Result<(), Self::Error> {
        let stream_status = conn.ready(Interest::READABLE | Interest::WRITABLE).await?;
        if stream_status.is_readable() && stream_status.is_writable() {
            Ok(())
        } else {
            Err(std::io::Error::new(ErrorKind::NotConnected, "When attempting to get connection from pool stream was not readable or writeable").into())
        }
    }

    fn has_broken(&self, _: &mut Self::Connection) -> bool {
        true
    }
}
```

**Comment by djc** [comment]
I can't think of a any gotchas, seems like a decent way to implement this.
