### ISSUE TITLE
What's in bb8 0.8.0?

### ISSUE THREAD

**Issue by punkeel** [djc/bb8#130]
Hi there! I've noticed that bb8 0.8.0 was released, but can't find a tagged commit (or a github release).

Looking at raw cargo data, I know 0.7.0: 7150f7cdb941eb455def1a3a0a75e20eae4914c7., 0.8.0: 87819652be715b2b2a65c2fa924e6e7d70af6ebe and can see the [diff](https://github.com/djc/bb8/compare/7150f7cdb941eb455def1a3a0a75e20eae4914c7...87819652be715b2b2a65c2fa924e6e7d70af6ebe) – but it would be much easier with tags

Was this on purpose? If not, could you please add git tags? 🙏

**Comment by djc** [comment]
I've added tags for 0.7.1 and 0.8.0. Hope that helps.

**Comment by punkeel** [comment]
Thank you!
