### ISSUE TITLE
ACL support for redis

### ISSUE THREAD

**Issue by SeriousBug** [djc/bb8#148]
Hey! Would it make sense to add ACL support to `bb8_redis`? My understanding is that when ACLs are enabled, each connection needs to execute `AUTH ...` before running other commands. I think it would make sense for `bb8_redis` to handle this so each new connection can execute the command before getting added into the pool. I'm happy to take a shot at this if it does make sense.

**Comment by djc** [comment]
It sounds like it might make sense, but it's hard to know for sure until I see a prototype implementation. Please submit a PR?

**Comment by SeriousBug** [comment]
Oh my bad, it actually looks like this is already built into `redis-rs` and can be used with `bb8_redis`. An example for anyone who comes across this issue:

```rust
let mut info = address.into_connection_info().unwrap();

info.redis.username = Some("user".to_string());
info.redis.password = Some("pass".to_string());

let manager = RedisConnectionManager::new(info)?;
let pool = Pool::builder().build(manager).await?;
```
