### ISSUE TITLE
Support for pool creation without requiring initial connection

### ISSUE THREAD

**Issue by dertin** [djc/bb8#172]
Is it possible that the application will not crash if the initial connection is not available at pool creation time? 
and a pool with a status of "pending connection" can be obtained.

I expect the errors to only be returned in pool.get() in case there is no connection. When the connection is disconnected after the pool creation the application continues to work and will try to connect only at the next pool.get().

**Comment by djc** [comment]
Can you set `min_idle` to 0?

**Comment by djc** [comment]
Closing this due to lack of response.
