### ISSUE TITLE
Lack of tests and coverage report

### ISSUE THREAD

**Issue by ar3s3ru** [djc/bb8#78]
Given the scope of the project, to ensure production-readiness an adequate testing suite should be added.

`cargo tarpaulin` might also give out a coverage report of the testing suite.

**Comment by djc** [comment]
I currently have limited time to dedicate to this project, so this isn't going to happen unless someone does the work, or if someone is willing to pay me to do the work.

**Comment by ar3s3ru** [comment]
Not implying you need to do the work on this yourself.

I can try to help out in this regard, with a little guidance :smile:

**Comment by djc** [comment]
What kind of guidance do you need? Do you have particular scenarios in mind that you think merit more coverage?

**Comment by djc** [comment]
@adrianbenavides added basic coverage in CI in #79.

**Comment by ar3s3ru** [comment]
Sorry I lost track of this issue, @adrianbenavides well done with the coverage job :clap:
