### ISSUE TITLE
Update to tokio 0.3

### ISSUE THREAD

**Issue by krojew** [djc/bb8#82]
Since tokio 0.3 [is out with some major changes](https://tokio.rs/blog/2020-10-tokio-0-3), it would be a good idea to update.

**Comment by djc** [comment]
bb8-redis depends on redis, which [needs to upgrade](https://github.com/mitsuhiko/redis-rs/issues/396).

**Comment by djc** [comment]
We also have an example that depends on [hyper](https://github.com/hyperium/hyper/issues/2302).

**Comment by krojew** [comment]
You can wrap them in tokio-compat-02.

**Comment by djc** [comment]
That seems like extra work, for the limited gain of having bb8 on tokio 0.3 a little sooner. I'm unlikely to do it (unless you want to fund the work), although I'll review it if you want to do the legwork.

**Comment by krojew** [comment]
The problem with bb8 on tokio 0.2 now is that it cannot be used by applications using 0.3, even with the compatibility layer. Any future returned by bb8 must be wrapped in a 0.2 wrapper, but if it then calls a future from 0.3, for example anything net related, the process panics.

**Comment by djc** [comment]
I'm aware of this, but I don't feel that keeping your application on 0.2 a little while longer is a big deal.

**Comment by djc** [comment]
I've pushed a [branch](https://github.com/djc/bb8/tree/tokio-0.3) which has bb8 and bb8-postgres working on tokio 0.3. I've temporarily removed the bb8-redis crate and the postgres hyper example from this branch, and will add them back as hyper/redis release new versions.

**Comment by djc** [comment]
Would be happy to get any feedback on this branch, but the changes were very minor anyway.

**Comment by krojew** [comment]
Looks like it's working.

**Comment by djc** [comment]
I've [released version 0.6.0](https://github.com/djc/bb8/releases/tag/v0.6.0) of bb8 and bb8-postgres with tokio 0.3 support.

**Comment by djc** [comment]
I've just released bb8-redis 0.7, which supports tokio 0.3.
