### ISSUE TITLE
Transferring the repository?

### ISSUE THREAD

**Issue by djc** [djc/bb8#85]
Hey @khuey, how would you feel about just transferring the repo to me? Would make it a bit easier to manage. You could still be a collaborator if you like -- not sure what your level of interest is these days. Let me know.

**Comment by khuey** [comment]
Sure.

**Comment by djc** [comment]
Thanks!

**Comment by khuey** [comment]
Feel free to change the order of our names in the authors list in Cargo.toml at some point too. I think it makes more sense to have the active maintainer listed first.

**Comment by djc** [comment]
Good point, done.
