### ISSUE TITLE
bb8_redis doesn't have the latest redis version

### ISSUE THREAD

**Issue by GopherJ** [djc/bb8#87]
![image](https://user-images.githubusercontent.com/33961674/98370194-764ecd80-203a-11eb-9c7a-fa6e9d45f63a.png)

**Comment by djc** [comment]
On master it depends on a later version, I think - please test and let me know if it works for you, I'll publish a release soon.

**Comment by GopherJ** [comment]
@djc yes I noticed it, thanks
