### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by luzhen1012** [djc/bb8#90]
@djc Hi, I was recently troubleshooting a memory leak, which may be related to connection pool. I saw that **spawn_start_connections** (method of PoolInner) locked on self.inner.internals, this is used to protect the entire spawn_replenishing_approvals method, right? I find that **spawn_replenishing_approvals** spawn a new task by tokio::spawn internally and without join or await on it,  locker won't protect the code in that this task, is this correct or expected?

**Comment by djc** [comment]
The `Mutex` used for `internals` cannot even live past await points, so you're right that the execution of the `spawn_replenishing_approvals()` and the futures it spawns are not protected by the lock acquired by `spawn_start_connections()`. Technically the lock is probably still held as `spawn_replenishing_approvals()` spawns its task, but it will be released soon after when `locked` in `spawn_start_connections()` returns to its caller.

Of course the `add_connection()` future set up inside `replenish_idle_connections()` will acquire the lock when necessary.

**Comment by luzhen1012** [comment]
> The `Mutex` used for `internals` cannot even live past await points, so you're right that the execution of the `spawn_replenishing_approvals()` and the futures it spawns are not protected by the lock acquired by `spawn_start_connections()`. Technically the lock is probably still held as `spawn_replenishing_approvals()` spawns its task, but it will be released soon after when `locked` in `spawn_start_connections()` returns to its caller.
> 
> Of course the `add_connection()` future set up inside `replenish_idle_connections()` will acquire the lock when necessary.
> 
> Hope that helps, let me know if you have any other questions!

According to your guidance, I find it is. Thank you very much for your reply！😄
